# 模型调用日志配置文件
version: 1
disable_existing_loggers: false

formatters:
  json:
    format: '%(message)s'
  detailed:
    format: '[%(asctime)s] %(name)s - %(levelname)s - %(message)s'
  simple:
    format: '%(levelname)s - %(message)s'

handlers:
  model_calls_file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/model_calls.jsonl
    maxBytes: 10485760  # 10MB
    backupCount: 5
    formatter: json
    encoding: utf-8
    level: INFO

  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  error_file:
    class: logging.FileHandler
    filename: logs/errors.log
    formatter: detailed
    encoding: utf-8
    level: ERROR

loggers:
  model_calls:
    level: INFO
    handlers: [model_calls_file, console]
    propagate: no

  app_errors:
    level: ERROR
    handlers: [error_file, console]
    propagate: no

root:
  level: INFO
  handlers: [console]
